// export About from './About/About';
export App from './App/App';
// export Chat from './Chat/Chat';
// export ChatFeathers from './ChatFeathers/ChatFeathers';
export Home from './Home/Home';
// export Login from './Login/Login';
// export LoginSuccess from './LoginSuccess/LoginSuccess';
export NotFound from './NotFound/NotFound';
// export Register from './Register/Register';
// export Survey from './Survey/Survey';
// export Widgets from './Widgets/Widgets';
