/* To avoid CSS expressions while still supporting IE 7 and IE 6, use this script */
/* The script tag referencing this file must be placed before the ending body tag. */

/* Use conditional comments in order to target IE 7 and older:
	<!--[if lt IE 8]><!-->
	<script src="ie7/ie7.js"></script>
	<!--<![endif]-->
*/

(function() {
	function addIcon(el, entity) {
		var html = el.innerHTML;
		el.innerHTML = '<span style="font-family: \'Basic-picto\'">' + entity + '</span>' + html;
	}
	var icons = {
		'basic-pictohome': '&#x5f;',
		'basic-pictofilecross': '&#x201c;',
		'basic-pictofiledownload': '&#x2018;',
		'basic-pictofileupload': '&#x7b;',
		'basic-pictofilecheck': '&#xb6;',
		'basic-pictopin': '&#x3c0;',
		'basic-pictotext': '&#x40;',
		'basic-pictobold': '&#x31;',
		'basic-pictoitalic': '&#x32;',
		'basic-pictounderline': '&#x33;',
		'basic-pictostrike': '&#xc1;',
		'basic-pictosymbol': '&#x2022;',
		'basic-pictosuperior': '&#xb0;',
		'basic-pictoindent-more': '&#xbb;',
		'basic-pictoindent-less': '&#xdb;',
		'basic-pictoliste': '&#x2260;',
		'basic-pictocalendar': '&#x41;',
		'basic-pictoverticalcircle': '&#x49;',
		'basic-pictopen2': '&#x6b;',
		'basic-pictosimply-down': '&#xa8;',
		'basic-pictosimply-left': '&#x3c;',
		'basic-pictosimply-right': '&#x3e;',
		'basic-pictosimply-up': '&#x5e;',
		'basic-pictobag': '&#xdf;',
		'basic-pictoshop': '&#x20ac;',
		'basic-pictosmarthphone': '&#x2030;',
		'basic-pictogoout': '&#xcf;',
		'basic-pictogoin': '&#xcd;',
		'basic-pictocode': '&#x2a;',
		'basic-pictoarrange': '&#xae;',
		'basic-pictochrono': '&#x2122;',
		'basic-pictotel': '&#x29;',
		'basic-pictocreditcard': '&#xa5;',
		'basic-pictoFilter': '&#xb7;',
		'basic-pictofemme': '&#x2039;',
		'basic-pictohomme': '&#xb5;',
		'basic-pictosquare_help': '&#x221e;',
		'basic-pictointerdict': '&#x6e;',
		'basic-pictomouse': '&#x7e;',
		'basic-pictofilter': '&#x131;',
		'basic-pictocar': '&#xbf;',
		'basic-pictoeye': '&#x65;',
		'basic-pictopaper-clip': '&#x220f;',
		'basic-pictomail': '&#x6d;',
		'basic-pictotoggle': '&#x79;',
		'basic-pictolayout': '&#x3a;',
		'basic-pictolink': '&#x6c;',
		'basic-pictobell': '&#x45;',
		'basic-pictolock': '&#x4c;',
		'basic-pictounlock': '&#x7c;',
		'basic-pictoribbon': '&#x2f;',
		'basic-pictoimage': '&#x69;',
		'basic-pictosignal': '&#x52;',
		'basic-pictotarget': '&#x153;',
		'basic-pictoclipboard': '&#x222b;',
		'basic-pictoclock': '&#x43;',
		'basic-pictowatch': '&#x77;',
		'basic-pictocamera': '&#x70;',
		'basic-pictovideo': '&#x76;',
		'basic-pictoair-play': '&#x59;',
		'basic-pictoprinter': '&#x50;',
		'basic-pictomonitor': '&#xd9;',
		'basic-pictocog': '&#x67;',
		'basic-pictoheart': '&#x68;',
		'basic-pictoheartfull': '&#x48;',
		'basic-pictostar': '&#x73;',
		'basic-pictostarfull': '&#x53;',
		'basic-pictoalign-justify': '&#x34;',
		'basic-pictoalign-left': '&#x35;',
		'basic-pictoalign-center': '&#x36;',
		'basic-pictoalign-right': '&#x37;',
		'basic-pictolayers': '&#x4f;',
		'basic-pictostack': '&#x221a;',
		'basic-pictostack-2': '&#x56;',
		'basic-pictopaper': '&#x6f;',
		'basic-pictopaper-stack': '&#x25ca;',
		'basic-pictosearch': '&#x7a;',
		'basic-pictozoom-in': '&#x5a;',
		'basic-pictozoom-out': '&#xc5;',
		'basic-pictorearward': '&#x42;',
		'basic-pictoforward': '&#x4e;',
		'basic-pictocircle-plus': '&#xb1;',
		'basic-pictocircle-minus': '&#x2013;',
		'basic-pictocircle-check': '&#xa2;',
		'basic-pictocircle-cross': '&#x2044;',
		'basic-pictosquare-plus': '&#xab;',
		'basic-pictosquare-minus': '&#xa1;',
		'basic-pictosquare-check': '&#xc7;',
		'basic-pictosquare-cross': '&#x7d;',
		'basic-pictomicrophone': '&#x60;',
		'basic-pictorecord': '&#x26;',
		'basic-pictoskip-back': '&#xe9;',
		'basic-pictorewind': '&#x22;',
		'basic-pictoplay': '&#x27;',
		'basic-pictopause': '&#x28;',
		'basic-pictostop': '&#xa7;',
		'basic-pictofast-forward': '&#xe8;',
		'basic-pictoskip-forward': '&#x21;',
		'basic-pictoshuffle': '&#xe7;',
		'basic-pictorepeat': '&#xe0;',
		'basic-pictofolder': '&#x66;',
		'basic-pictoumbrella': '&#xb4;',
		'basic-pictomoon': '&#x201e;',
		'basic-pictothermometer': '&#x201d;',
		'basic-pictodrop': '&#x2019;',
		'basic-pictosun': '&#x5b;',
		'basic-pictocloud': '&#xe5;',
		'basic-pictocloud-upload': '&#xaa;',
		'basic-pictocloud-download': '&#x2206;',
		'basic-pictoupload': '&#x55;',
		'basic-pictodownload': '&#x44;',
		'basic-pictolocation': '&#xd3;',
		'basic-pictolocation-2': '&#x4d;',
		'basic-pictomap': '&#x25;',
		'basic-pictobattery': '&#x2e;',
		'basic-pictohead': '&#x6a;',
		'basic-pictobriefcase': '&#x24;',
		'basic-pictospeech-bubble': '&#x62;',
		'basic-pictoanchor': '&#xe6;',
		'basic-pictoglobe': '&#x57;',
		'basic-pictoreload': '&#x72;',
		'basic-pictoshare': '&#x61;',
		'basic-pictotag': '&#x2020;',
		'basic-pictopower': '&#x71;',
		'basic-pictocommand': '&#x23;',
		'basic-pictoalt': '&#xc6;',
		'basic-pictobar-graph': '&#x47;',
		'basic-pictobar-graph-2': '&#xfb02;',
		'basic-pictopie-graph': '&#xa9;',
		'basic-pictoarrow-left': '&#x2264;',
		'basic-pictoarrow-right': '&#x2265;',
		'basic-pictoarrow-up': '&#xf4;',
		'basic-pictoarrow-down': '&#xd4;',
		'basic-pictovolume': '&#xd2;',
		'basic-pictomute': '&#x2211;',
		'basic-pictogrid-2': '&#xfb01;',
		'basic-pictoloader': '&#xac;',
		'basic-pictoban': '&#x5c;',
		'basic-pictoflag': '&#x192;',
		'basic-pictotrash': '&#x74;',
		'basic-pictoexpand': '&#xee;',
		'basic-pictocontract': '&#xef;',
		'basic-pictomaximize': '&#x3f;',
		'basic-pictominimize': '&#x2c;',
		'basic-pictoplus': '&#x2b;',
		'basic-pictominus': '&#x2d;',
		'basic-pictocheck': '&#x63;',
		'basic-pictocross': '&#x78;',
		'basic-pictomove': '&#xf9;',
		'basic-pictodelete': '&#x54;',
		'basic-pictomenu': '&#x3d;',
		'basic-pictoarchive': '&#xc2;',
		'basic-pictoinbox': '&#x64;',
		'basic-pictooutbox': '&#x75;',
		'basic-pictofile': '&#x46;',
		'basic-pictofile-add': '&#xf8ff;',
		'basic-pictofile-subtract': '&#xeb;',
		'basic-pictohelp': '&#xcc;',
		'basic-pictoopen': '&#x152;',
		'basic-pictoellipsis': '&#x2026;',
		'basic-pictobox': '&#x3b;',
		'basic-pictobook': '&#xf8;',
		'basic-pictomarquee-plus': '&#xf7;',
		'basic-pictomarquee-minus': '&#x2014;',
		'basic-pictocolumns': '&#x5d;',
		'basic-pictocontent-right': '&#x38;',
		'basic-pictocontent-left': '&#x39;',
		'basic-pictogrid': '&#x30;',
		'basic-pictodisc': '&#x51;',
		'basic-pictoserver': '&#xc8;',
		'0': 0
		},
		els = document.getElementsByTagName('*'),
		i, c, el;
	for (i = 0; ; i += 1) {
		el = els[i];
		if(!el) {
			break;
		}
		c = el.className;
		c = c.match(/basic-picto[^\s'"]+/);
		if (c && icons[c[0]]) {
			addIcon(el, icons[c[0]]);
		}
	}
}());
